  0%|                                                                                                                          | 0/370 [00:00<?, ?it/s]/home/st-aleksandr-razin/.conda/envs/qc4qa/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py:321: UserWarning: MatMul8bitLt: inputs will be cast from torch.float32 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
Traceback (most recent call last):
  File "/home/st-aleksandr-razin/workspace/SRC_QC4QA/QA_pipeline/scripts/train_script.py", line 139, in <module>
    main()
  File "/home/st-aleksandr-razin/.conda/envs/qc4qa/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/st-aleksandr-razin/.conda/envs/qc4qa/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/st-aleksandr-razin/.conda/envs/qc4qa/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/st-aleksandr-razin/.conda/envs/qc4qa/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/st-aleksandr-razin/workspace/SRC_QC4QA/QA_pipeline/scripts/train_script.py", line 133, in main
    trainer.train(config["training_arguments"]["resume_from_checkpoint"])
  File "/home/st-aleksandr-razin/.conda/envs/qc4qa/lib/python3.10/site-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
  File "/home/st-aleksandr-razin/.conda/envs/qc4qa/lib/python3.10/site-packages/transformers/trainer.py", line 1802, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/st-aleksandr-razin/.conda/envs/qc4qa/lib/python3.10/site-packages/transformers/trainer.py", line 2658, in training_step
    self.accelerator.backward(loss)
  File "/home/st-aleksandr-razin/.conda/envs/qc4qa/lib/python3.10/site-packages/accelerate/accelerator.py", line 1819, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "/home/st-aleksandr-razin/.conda/envs/qc4qa/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/st-aleksandr-razin/.conda/envs/qc4qa/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/st-aleksandr-razin/.conda/envs/qc4qa/lib/python3.10/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/home/st-aleksandr-razin/.conda/envs/qc4qa/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 157, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/home/st-aleksandr-razin/.conda/envs/qc4qa/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 6.25 GiB (GPU 0; 79.35 GiB total capacity; 62.37 GiB already allocated; 1.66 GiB free; 76.49 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF